server:
  port: 8080

spring:
  application:
    name: GISuite

  datasource:
    url: jdbc:postgresql://98.84.134.140:5432/
    username:
    password:
    driver-class-name: org.postgresql.Driver
    hikari:
        maximum-pool-size: 10
        minimum-idle: 2
        idle-timeout: 30000
        connection-timeout: 30000
        max-lifetime: 1800000

  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        hbm2ddl.auto: update
        max_fetch_depth: 5
        dialect: org.hibernate.dialect.PostgreSQLDialect


logging:
  level:
    org:
      springframework: INFO
      hibernate: DEBUG

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
